# Configuration file for embedding model evaluation

# 1. Data Source Configuration
data_source:
  type: pdf                                     # str: Data source type - 'csv', 'oracle', 'json', 'txt', 'pdf'
  file: 'data/pdf_files/jesc1*.pdf'            # str: Path to data file(s), supports glob patterns
  
  # PDF-specific settings (used when type: pdf)
  pdf_config:
    extract_tables: true                        # bool: Extract tables from PDF documents
    include_metadata: true                      # bool: Include PDF metadata in embeddings
    ocr_enabled: false                          # bool: Enable OCR for scanned documents
    
  # CSV/Database settings (used when type: csv/oracle)
  structured_config:
    embed_columns: all                          # str/list: 'all' or list of columns to embed
    delimiter: ","                              # str: CSV delimiter character
    
  # Oracle connection (used when type: oracle)
  oracle_config:
    host: localhost                             # str: Database host
    port: 1521                                  # int: Database port
    sid: XE                                     # str: Database SID
    user: null                                  # str: Database username
    password: null                              # str: Database password
    table: null                                 # str: Target table name
#"vprelovac_universe-sentence-encoder_4", 
# 2. Embedding Configuration
embed_config:
  model: "sentence-transformers/all-MiniLM-L6-v2"  # str:  model
  
  # Processing parameters
  batch_size: 256                                   # int: Batch size for embedding generation
  normalize: true                                   # bool: Whether to normalize embeddings
  dimension: 384                                    # int: Target embedding dimension
  embedding_type: semantic                          # str: 'semantic', 'dense', 'sparse', 'hybrid'
  
  # Optimization settings
  optimization:
    use_gpu: true                                  # bool: Enable GPU acceleration
    half_precision: true                           # bool: Use FP16 for faster processing
    num_workers: 8                                 # int: Number of CPU workers for data loading
  
  # Dimension reduction settings
  dimension_reduction:
    use_pca: true                                 # bool: Enable PCA reduction
    random_state: 42                              # int: Random seed for reproducibility
    whiten: false                                 # bool: Scale components to unit variance
  # For OpenAI/Cohere models, add api_key fields as needed
  # openai_api_key: sk-...
  # cohere_api_key: ...

# 3. Chunking Parameters
chunking:
  strategy: sentence             # str: 'none', 'sentence', 'sliding_window', 'fixed_length', 'paragraph'
  chunk_size: 1000               # int: Size of chunks (characters for fixed/sliding, target size for sentence/paragraph)
  overlap: 100                   # int: Overlap size for sliding window strategy
  delimiter: "\n\n"              # str: Delimiter for paragraph chunking
  combine_small_chunks: true     # bool: Whether to combine small chunks
  min_chunk_size: 100            # int: Minimum chunk size when combining
  sentence_options:
    language: english            # str: Language for sentence tokenization
    respect_breaks: true         # bool: Whether to respect line breaks
  advanced:
    normalize_whitespace: true   # bool: Clean up excessive whitespace
    preserve_line_breaks: false  # bool: Keep original line breaks in output
    smart_splitting: true        # bool: Try to split at semantic boundaries

# 4. Vector Database Connection Details
vector_db:
  type: qdrant                    # str: 'Milvus', 'Qdrant'
  host: localhost                 # str: Database host address
  port: 6333                      # int: Database port (Qdrant default: 6333, Milvus default: 19530)
  collection: science_embeddings  # str: Collection name prefix
  
  # Connection settings
  connection_retries: 3          # int: Number of connection retry attempts
  retry_delay: 5                 # int: Seconds to wait between retries
  timeout: 300                   # int: Operation timeout in seconds
  
  # Batch processing
  batch_size: 300               # int: Batch size for DB insertion (default: 500)
  upsert_retries: 3            # int: Number of retries for failed upserts
  upsert_retry_delay: 2        # int: Delay (seconds) between upsert retries
  # Indexing configuration for Qdrant

  vector_index:
    type: hnsw                    # str: 'plain', 'hnsw', 'ivf'
    params:
      m: 16                       # Number of edges per node in the index graph
      ef_construct: 256           # Size of the dynamic candidate list for construction
      ef_runtime: 128             # Size of the dynamic candidate list at search time
      full_scan_threshold: 10000  # Number of vectors to trigger full scan optimization
    quantization:
      enabled: true              # Whether to enable scalar quantization
      always_ram: true           # Keep quantized vectors in RAM
      quantum: 0.01              # Quantization step
  payload_index:
    - field: page_number         # For PDF documents
      type: integer
    - field: chunk_index
      type: integer
    - field: total_chunks
      type: integer
    - field: chunk_size
      type: integer
    - field: chunking_strategy
      type: keyword
    - field: content_type       # Type of content (text, table, etc.)
      type: keyword
    - field: metadata           # For document metadata
      type: object
      schema:
        title: keyword
        author: keyword
        date: date
        timeeval_only: false  
  #payload_index:
  #  - field: Origin
  #    type: keyword
  #  - field: FlightDate
  #    type: datetime
  #  - field: DepDelayMinutes
  #    type: float 
              
 
# 5. Retrieval & Evaluation Parameters
retrieval:
  enabled: true                   # bool
  top_k: 10                       # Increased for better recall
  score_threshold: 0.4          # Slightly lowered threshold for more results
  metric_type: COSINE            # str: 'L2', 'IP', 'COSINE', 'EUCLID', 'DOT'
  nprobe: 256                    # Increased for better search accuracy (Milvus)
  distance: COSINE               # str (Qdrant): 'COSINE', 'EUCLID', 'DOT'
  filter: ""                     # str: filter expression (if supported)
  semantic_query: "what is right thumb rule ? explain it" #"Find flights departing from Indianapolis International Airport (IND) on April 1st 2022 which experienced departure delays" # More specific query
  rerank_results: true          # Enable reranking for better relevance
  diversity_weight: 0.2         # Lowered to prioritize relevancerameter are shown in comments
  #payload_filter:
  #  must:
  #    - key: "Origin"
  #      match:
  #        value: "IND"
  #    - key: "FlightDate"
  #      match:
  #        value: "2022-04-01"
  #    - key: "DepDelayMinutes"
  #      range:
  #        gte: 37
  order_by:
    - field: DepDelayMinutes
      order: desc
  #payload_filter:
    #origin: "IND"
    #DepDelayMinutes:
    #  gte: 1
    #FlightDate: 2022-04-01
      #gte: "2022-04-01"
      #lte: "2022-04-01"

# 6. Evaluation Configuration
evaluation:
  relevant_ids: [531]                           # list[int]: Ground truth relevant IDs
  metrics: [                                    # list[str]: Metrics to compute
    accuracy,
    recall, 
    precision,
    f1
  ]

# 7. Debug Configuration
debug:
  retrieval_only: false                         # bool: Run only retrieval tests
